name: Build and deploy package site

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
      statuses: write
    steps:
      - uses: actions/checkout@HEAD

      - uses: r-lib/actions/setup-r@HEAD
        with:
          use-public-rspm: true
      - uses: yihui/actions/setup-r-dependencies@HEAD
        with:
          extra-packages: litedown xfun gsDesign2 .
          r-universe: yihui
      - uses: yihui/actions/litedown-site@HEAD
        with:
          site-dir: 'site'

      - if: github.event_name == 'pull_request'
        id: upload
        uses: actions/upload-artifact@HEAD
        with:
          name: site-preview
          path: 'site'

      - if: github.event_name == 'pull_request'
        uses: actions/github-script@HEAD
        with:
          script: |
            const runUrl = `${{ steps.upload.outputs.artifact-url }}`;
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              state: 'success',
              target_url: runUrl,
              description: 'Site preview artifact ready',
              context: 'Site preview'
            });

      - name: Deploy to gh-pages
        if: github.event_name != 'pull_request'
        run: |
          cd site
          git init
          git checkout -b gh-pages
          git add .
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "deploy site"
          git push -f "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" gh-pages
